news/urls.py
from django.urls import path
from news import views

urlpatterns = [
    path('new-list/', views.NewListView.as_view(), name='new-list'),
    path('new-create/', views.NewCreateView.as_view(), name="new-create"),
    path('new-update/<int:pk>/', views.NewUpdateView.as_view(), name="new-update"),
    path('new-delete/<int:pk>/', views.NewDeleteView.as_view(), name="new-delete")
]

app_name = "news"

polls/urls.py
from django.urls import path
from polls import views

urlpatterns = [
    path("questions/", views.QuestionListView.as_view(), name="question-list"),
    path("question/<int:pk>/", views.QuestionDetailView.as_view(), name="question-detail"),
    path("question-create/", views.QuestionCreateView.as_view(), name="question-create"),
    path("question-update/<int:pk>/", views.QuestionUpdateView.as_view(), name="question-update"),
    path("question-delete/<int:pk>/", views.QuestionDeleteView.as_view(), name="question-delete"),
    path("choice-update/<int:pk>/", views.ChoiceUpdateView.as_view(), name="choice-update"),
    path("choice-delete/<int:pk>/", views.ChoiceDeleteView.as_view(), name="choice-delete"),
    path("error-answer/<int:question_id>/", views.error_answer_view, name="error-answer")
]

app_name="polls"

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_page.urls")),
    path('ins/', include('institutions.urls')),
    path("auth/", include("auth_system.urls")),
    path("ad/", include("adverts.urls")),
    path('ev/', include('events.urls')),
    path("walking/", include("walking.urls")),
    path("polls/", include("polls.urls")),
    path("news/", include("news.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

polls/models.py
from django.db import models
from auth_system.models import *
# Create your models here.

class Question(models.Model):
    text = models.CharField(max_length=256)

    def __str__(self):
        return f'Питання #{self.pk}'

    class Meta:
        verbose_name = "Question"
        verbose_name_plural = "Questions"
        ordering = ['pk']

class Choice(models.Model):
    respond = models.CharField(max_length=256)
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="choices")

    def show_persent(self):
        number_answers = len(Answer.objects.filter(question=self.question).all())
        number_this_answers = len(Answer.objects.filter(choice=self).all())
        if number_answers == 0 or number_this_answers == 0:
            return 0
        percent = int((number_this_answers * 100) / number_answers)
        return percent

    def __str__(self):
        return f'Відповідь  до питання #{self.question.pk} - {self.respond}'

    class Meta:
        verbose_name = "Choice"
        verbose_name_plural = "Choices"


class Answer(models.Model):
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, related_name="answers")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers_q", null=True, blank="True")
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f'Відповідь {self.user.username} до питання #{self.question.pk}'

    class Meta:
        verbose_name = "Answer"
        verbose_name_plural = "Answers"
        unique_together = [["user", "question"]]

polls/forms.py
from django import forms
from polls.models import Answer, Choice, Question

class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['choice']

    def __init__(self, *args, **kwargs):
        question = kwargs.pop('question', None)
        super().__init__(*args, **kwargs)
        if question:
            self.fields['choice'].queryset = Choice.objects.filter(question=question)
        self.fields["choice"].widget.attrs.update({"class": "form-control"})


class ChoiceForm(forms.ModelForm):
    class Meta:
        model = Choice
        fields = ['respond']

    def __init__(self, *args, **kwargs):
        super(ChoiceForm, self).__init__(*args, **kwargs)
        self.fields["respond"].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Respond..."})
        self.fields["respond"].label = ""

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['text']

    def __init__(self, *args, **kwargs):
        super(QuestionForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs.update({
                "class": "form-control",
                "placeholder": "Питання...  ",
                })
        self.fields['text'].label = ''

polls/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from polls.models import *
from auth_system.models import *
from polls.mixing import *
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from polls.forms import AnswerForm, ChoiceForm, QuestionForm
from django.shortcuts import get_object_or_404

# Create your views here.


class QuestionListView(ListView):
    model = Question
    template_name = "polls/question-list.html"
    context_object_name = "questions"

class QuestionDetailView(DetailView):
    model = Question
    template_name = "polls/question-detail.html"
    context_object_name = "question"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        question = self.get_object()
        answers = Answer.objects.filter(question=question).all()
        context['answer_form'] = AnswerForm(question=question)
        context['choice_form'] = ChoiceForm()
        return context

    @method_decorator(login_required)
    def post(self, request, *args, **kwargs):
        action = request.POST.get('action_type')

        if action == 'answer':
            return self.answer_post(request)
        elif action == 'add_choice':
            return self.add_choice_post(request)
        else:
            return super().post(request, *args, **kwargs)

    def answer_post(self, request):
        question = self.get_object()
        answer_form = AnswerForm(request.POST, question=question)
        if answer_form.is_valid():
            answer = answer_form.save(commit=False)
            answer.user = request.user
            answer.question = question
            answer_qs = Answer.objects.filter(user=request.user, question=question)
            if answer_qs.exists():
                return redirect("polls:error-answer", question_id=question.pk)
            else:
                answer.save()
            return redirect('polls:question-detail', pk=question.pk)
        else:
            pass
    #
    # class CommentLikeToggle(LoginRequiredMixin, View):
    #     def post(self, request, *args, **kwargs):
    #         comment = get_object_or_404(Comment, pk=self.kwargs.get('pk'))
    #         like_qs = Like.objects.filter(comment=comment, user=request.user)
    #         if like_qs.exists():
    #             like_qs.delete()
    #         else:
    #             Like.objects.create(comment=comment, user=request.user)
    #         return redirect('tasks:task-detail', pk=comment.task.pk)

    def add_choice_post(self, request):
        if not request.user.admin_or_moder():
            raise PermissionDenied
        choice_form = ChoiceForm(request.POST)
        if choice_form.is_valid():
            choice = choice_form.save(commit=False)
            choice.question = self.get_object()
            choice.save()
            return redirect('polls:question-detail', pk=choice.question.pk)
        else:
            pass

def error_answer_view(request, question_id):
    question = Question.objects.get(pk=question_id)
    return render(request, template_name="polls/error-answer.html", context={"question": question})

class QuestionCreateView(LoginRequiredMixin, UserIsAdminOrModerMixin, CreateView):
    model = Question
    template_name = "polls/question-create.html"
    context_object_name = "question"
    form_class = QuestionForm

    def get_success_url(self):
        return reverse_lazy("polls:question-detail", kwargs={'pk': self.object.pk})


class QuestionUpdateView(LoginRequiredMixin, UserIsAdminOrModerMixin, UpdateView):
    model = Question
    template_name = "polls/question-update.html"
    form_class = QuestionForm
    context_object_name = "question"

    def get_success_url(self):
        return reverse_lazy("polls:question-detail", kwargs={'pk': self.object.pk})


class QuestionDeleteView(LoginRequiredMixin, UserIsAdminOrModerMixin, DeleteView):
    model = Question
    context_object_name = "question"
    success_url = reverse_lazy("polls:question-list")


class ChoiceUpdateView(LoginRequiredMixin, UserIsAdminOrModerMixin, UpdateView):
    model = Choice
    template_name = "polls/choice-update.html"
    form_class = ChoiceForm
    context_object_name = "choice"

    def get_success_url(self):
        return reverse_lazy("polls:question-detail", kwargs={'pk': self.object.question.pk})


class ChoiceDeleteView(LoginRequiredMixin, UserIsAdminOrModerMixin, DeleteView):
    model = Choice
    context_object_name = "choice"

    def get_success_url(self):
        return reverse_lazy("polls:question-detail", kwargs={'pk': self.object.question.pk})

templates/polls/choice-update.html
{% extends "base.html" %}
{% block content %}
<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-div-polls">
            <br>
            <h1 class="def-text" style="text-align: center;">Оновлення відповіді</h1>
            <br>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Змінити</button>
                <a href = "{% url 'polls:question-detail' choice.question.pk %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



{% endblock %}

templates/polls/error-answer.html
{% extends "base.html" %}

{% block content %}

<div class="container-sm container-md container-lg">
    <br>
    <h1 style="text-align:center; color: red"><b>Ти вже відповів!!! - <a class="btn btn-secondary" href="{% url 'polls:question-detail' question.pk %}">Назад</a></b></h1>
    <br>
</div>

{% endblock %}

templates/polls/question-create.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-div-polls">
            <br>
            <h1 class="def-text" style="text-align: center;">Створення опитування</h1>
            <br>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-danger">Cтворити</button>
                <a href = "{% url 'polls:question-list' %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>


{% endblock %}

templates/polls/question-detail.html
{% extends "base.html" %}

{% block content %}
{% load static %}

<br>
<br>
<br>
<h1 class="def-text" style="text-align: center; font-weight: 700"><i>{{ question.text }}</i></h1>
{% if request.user.admin_or_moder %}
    <br>
    <br>
    <br>
    <div class="row">
        <div class="col-sm-10 col-md-10 col-lg-10"></div>
        <div class="col-sm-1 col-md-1 col-lg-1">
            <a class="btn btn-warning" href="{% url 'polls:question-update' question.pk %}">Редагувати</a>
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
            <form action="{% url 'polls:question-delete' question.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" onclick="return confirm('Ви справді хочете видалити це питання?')">Видалити</button>
            </form>
        </div>
    </div>
{% endif %}

<br>
<br>
<hr>
<br>
<form method="post" action="{% url 'polls:question-detail' question.pk %}">
    {% csrf_token %}
    <div class="row">
    {% for choice in answer_form.fields.choice.queryset %}
        <div class="col-sm-3 col-md-3 col-lg-3">
            <button type="submit" name="choice" value="{{ choice.id }}" class="btn-choice">
                {{ choice.respond }}
            </button>
            <br>
            <div class="progress">
                <div class="progress-bar" style="width:{{ choice.show_persent }}%">{{ choice.show_persent }}%</div>
            </div>
            <br>
            <br>
        </div>
    {% endfor %}
    </div>
    <br>
    <br>
    <h5 class="def-text" style="text-align: right;">*Обери один з варінатів...</h5>
    <input type="hidden" name="action_type" value="answer">
</form>
<br>
{% if request.user.admin_or_moder %}
<br>
<div class="row">
    <div class="col-sm-10 col-md-10 col-lg-10"></div>
    <div class="col-sm-1 col-md-1 col-lg-1">
        <button class="btn btn-dark" onclick="show_settings()" ondblclick="hide_settings()">Налаштування</button>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
</div>

<br>
<div id="settings" style="display: none">
    <div class="row">
        <div class="col-sm-3 col-md-3 col-lg-3"></div>
        <div class="col-sm-6 col-md-6 col-lg-6">
            <div class="settings">
                <br>
                <h3 class="def-text" style="text-align:center;">Налаштування відповідей</h3>
                <br>
                <form method="post" action="{% url 'polls:question-detail' question.pk %}">
                    {% csrf_token %}
                    {{ choice_form.as_p }}
                    <input type="hidden" name="action_type" value="add_choice">
                    <button type="submit" class="btn btn-primary">Додати</button>
                </form>
                <br>
                <hr>
                    <ul>
                       {% for choice in question.choices.all %}
                        <li>
                            <h6>
                                <b>{{ choice.respond }}</b>
                                <a class="btn btn-warning" href="{% url 'polls:choice-update' choice.pk %}">Редагувати</a>
                            </h6>
                        </li>
                        <h6><b>Відсоток відповідей</b> - {{ choice.show_persent }}%</h6>
                         <form action="{% url 'polls:choice-delete' choice.pk %}" method="POST">
                             {% csrf_token %}
                             <button type="submit" class="btn btn-danger" onclick="return confirm('Ви справді хочете видалити цю відповідь?')">Видалити</button>
                         </form>
                        <hr>
                        {% endfor %}
                    </ul>

            </div>
        </div>
        <div class="col-sm-3 col-md-3 col-lg-3"></div>
    </div>
</div>
{% endif %}
<br>
<br>
<br>
<br>
<br>
<br>

<script>
    function show_settings(){
        document.getElementById("settings").style.display = 'block';
    }
    function hide_settings(){
        document.getElementById("settings").style.display = 'none';
    };
</script>

<script>
    // Масив кольорів веселки
    const colors = [
        '#FF6666', // Темно-червоний
        '#FF9966', // Темно-оранжевий
        '#FFCC66', // Темно-жовтий
        '#66CC66', // Темно-зелений
        '#66CCCC', // Темно-блакитний
        '#6666CC', // Темно-синій
        '#9966CC'  // Темно-фіолетовий
    ];

    // Отримуємо всі кнопки та прогрес-бари
    const buttons = document.querySelectorAll('.btn-choice');
    const progresses = document.querySelectorAll('.progress-bar');

    // Призначаємо випадковий колір кожній кнопці і відповідному прогрес-бару
    buttons.forEach((button, index) => {
        const randomColor = colors[Math.floor(Math.random() * colors.length)];
        button.style.backgroundColor = randomColor;

        // Перевіряємо, чи є відповідний прогрес-бар
        if (progresses[index]) {
            progresses[index].style.backgroundColor = randomColor;
        }
    });
</script>


{% endblock %}

templates/polls/question-list.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<br>
<br>
{% if request.user.role == "admin" or request.user.role == "moderator" %}
    <div class="row">
        <div class="col-sm-2 col-md-2 col-lg-2"></div>
        <div class="col-sm-8 col-md-8 col-lg-8">
            <a class="btn btn-create-ques" href="{% url 'polls:question-create' %}" ><i>Створити питання</i></a>
        </div>
        <div class="col-sm-2 col-md-2 col-lg-2"></div>
    </div>
{% endif %}
<br>
<br>
<div class="row">
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
    <div class="col-sm-10 col-md-10 col-lg-10">
        <br>
        {% for question in questions %}
            <a href = "{% url 'polls:question-detail' question.pk %}" class="a-poll">
                <div class="question-div">
                    <h2 class="def-text">{{ question.text }}</h2>
                </div>
            </a>
            <br>
            <br>
        {% empty %}
        <h2 class="def-text" style="text-align:center"><i>Немає опитувань...</i></h2>
        {% endfor %}
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/polls/question-update.html
{% extends "base.html" %}
{% block content %}


{% load static %}
<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-div-polls">
            <br>
            <h1 class="def-text" style="text-align: center;">Оновлення питання</h1>
            <br>
            <form method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <br>
              <button type="submit" class="btn btn-danger">Змінити</button>
              <a href = "{% url 'polls:question-detail' question.pk %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}