institutions/urls.py
from django.urls import path
from institutions import views

urlpatterns = [
    path('insts/', views.InstitutionListView.as_view(), name="ins-list"),
    path('ins/<int:pk>/', views.InstitutionDetailView.as_view(), name="ins-detail"),
    path("review-update/<int:pk>/", views.ReviewUpdateView.as_view(), name="review-update"),
    path("review-delete/<int:pk>/", views.ReviewDeleteView.as_view(), name="review-delete"),
    path("add-ins", views.InstitutionCreateView.as_view(), name="add-ins"),
    path("update-ins/<int:pk>/", views.InstitutionUpdateView.as_view(), name="update-ins"),
    path("delete-ins/<int:pk>/", views.InstitutionDeleteView.as_view(), name="delete-ins"),
    path('search/results/', views.SearchView.as_view(), name='search_view'),
    ]

app_name = "ins"

news/urls.py
from django.urls import path
from news import views

urlpatterns = [
    path('new-list/', views.NewListView.as_view(), name='new-list'),
    path('new-create/', views.NewCreateView.as_view(), name="new-create"),
    path('new-update/<int:pk>/', views.NewUpdateView.as_view(), name="new-update"),
    path('new-delete/<int:pk>/', views.NewDeleteView.as_view(), name="new-delete")
]

app_name = "news"

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_page.urls")),
    path('ins/', include('institutions.urls')),
    path("auth/", include("auth_system.urls")),
    path("ad/", include("adverts.urls")),
    path('ev/', include('events.urls')),
    path("walking/", include("walking.urls")),
    path("polls/", include("polls.urls")),
    path("news/", include("news.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/ins/ins-create.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-create-ins">
            <br>
            <h1 class="def-text" style="text-align: center;">Додавання закладу</h1>
            <br>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <br>
              <button type="submit" class="btn btn-primary">Додати</button>
              <a href = "{% url 'ins:ins-list' %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/ins/ins-detail.html
{% extends "base.html" %}
{% block content %}
{% load static %}

<div class="row">
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
    <div class="col-sm-10 col-md-10 col-lg-10">
        <h1 class="def-text back-img" style="text-align: center;"><b>{{ ins.name }}</b></h1>
        <br>
        <div class="row">
            <div class="col-md-9">
                <div class="desc-ins">
                     <p class="def-text" style="font-size: 18px;">{{ ins.description }}</p>
                </div>
            </div>
            <div class="col-md-3">
                <div class="desc-ins" style="padding:20px;">
                    <h4>Тип:
                        {% if ins.type == "Catering" %}
                            <img src="{% static 'images/ins/catering.png' %}" style="width: 55px; height:auto">
                        {% elif ins.type == "Sport" %}
                            <img src="{% static 'images/ins/sport.png!sw800' %}" style="width: 50px; height:auto">
                        {% elif ins.type == "Entertainment" %}
                            <img src="{% static 'images/ins/entertainment.png' %}" style="width: 35px; height:auto">
                        {% elif ins.type == "Education" %}
                            <img src="{% static 'images/ins/education.png' %}" style="width: 40px; height:auto">
                        {% elif ins.type == "Trade" %}
                            <img src="{% static 'images/ins/trade.png' %}" style="width: 35px; height:auto">
                        {% elif ins.type == "Hotels" %}
                            <img src="{% static 'images/ins/hotels.png' %}" style="width: 30px; height:auto">
                        {% elif ins.type == "Beauty and health" %}
                            <img src="{% static 'images/ins/beauty_health.png' %}" style="width: 40px; height:auto">
                        {% endif %}
                    </h4>
                    <h4>Локаіція: <a href="{{ ins.location }}"> <img src="{% static 'images/ins/location-ins.png' %}" style="width: 20px; height:auto"></a></h4>
                    <h4>Рейтинг: {{ ins.rating }}</h4>
                    <div class="progress">
                      <div class="progress-bar" style='width:{{ ins.rating }}%;'>
                        {{ ins.rating }}
                      </div>
            </div>
                </div>
            </div>

        </div>

        <br>
        <br>
        {% if request.user.admin_or_moder %}
            <a href="{% url 'ins:update-ins' ins.pk %}" class="btn btn-warning">Редагувати</a>
            <br>
            <br>
            <form action="{% url 'ins:delete-ins' ins.pk %}" method="POST">
                {% csrf_token %}
                <button type="submit" class="btn btn-danger" onclick="return confirm('Ви справді хочете видалити цей заклад?')">Видалити</button>
            </form>
            <br>
        {% endif %}
        <a href="{% url 'ins:ins-list' %}" class="btn btn-secondary">Назад</a>
        <br>
        <br>
        <br>
        <br>
        <div class="review-div">
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-3">
                    {% if request.user.media %}
                        <h5 class="def-text"><img src="{{ request.user.media.url }}" style="width: 40px; height: 40px; border-radius: 50%;"> <b>{{ request.user.username }}</b></h5>
                    {% else %}
                        <h5><img src="{% static 'images/auth/user-icon.png' %}" style="width: 45px; height: auto;"> <b>{{ request.user.username }}</b></h5>
                    {% endif %}
                </div>
                <div class="col-sm-8 col-md-8 col-lg-8"></div>
                <div class="col-sm-1 col-md-1 col-lg-1">
                    <img src="{% static 'images/ins/edit.png' %}" class="img-btn"> <img src="{% static 'images/ins/delete.png' %}" class="img-btn">
                </div>
                </div>
                  <hr>
                  <form action="{% url 'ins:ins-detail' ins.pk %}" method="post">
                      {% csrf_token %}
                      <p class="def-text" style="white-space: wrap;">
                          <br>
                          {{ review_form.text }}
                          <br>
                      </p>
                      <hr>
                      <div class="row">
                          <div class="col-sm-3 col-md-3 col-lg-3">
                              <p>
                                  {{ review_form.rate }}
                              </p>
                          </div>
                          <div class="col-sm-8 col-md-8 col-lg-8"></div>
                          <div class="col-sm-1 col-md-1 col-lg-1">
                              <p><img src = "{% static 'images/ins/time.png' %}" class="img-btn"></p>
                          </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-11 col-md-11 col-lg-11"></div>
                        <div class="col-sm-1 col-md-1 col-lg-1">
                            <button type="submit" class="btn">
                                <img src="{% static 'images/ins/send.png' %}" style="max-width: 100%; height: auto">
                            </button>
                        </div>
                    </div>
                  </form>

              </div>
            <br>
            {% for review in reviews %}
              <div class="review-div">
                  <div class="row">
                      <div class="col-sm-3 col-md-3 col-lg-3">
                          {% if review.user.media %}
                            <h5 class="def-text"><img src="{{ review.user.media.url }}" style="width: 40px; height: 40px; border-radius: 50%;"> <b>{{review.user.username}}</b></h5>
                          {% else %}
                            <h5><img src="{% static 'images/auth/user-icon.png' %}" style="width: 45px; height: auto;"><b>{{review.user.username}}</b></h5>
                          {% endif %}
                      </div>
                      <div class="col-sm-7 col-md-7 col-lg-7"></div>
                      {% if review.user == request.user %}
                          <div class="col-sm-1 col-md-1 col-lg-1">
                              <button style="margin-left: 50px;" class="btn"><a href="{% url 'ins:review-update' review.pk %}"><img src="{% static 'images/ins/edit.png' %}" class="img-btn"></a></button>
                          </div>
                          <div class="col-sm-1 col-md-1 col-lg-1">
                              <form action="{% url 'ins:review-delete' review.pk %}" method="POST" >
                                    {% csrf_token %}
                                    <button type="submit" class="btn" onclick="return confirm('Ви справді хочете видалити цей відгук?')"><img src="{% static 'images/ins/delete.png' %}" class="img-btn" ></button>
                              </form>
                          </div>
                      {% else %}
                            <div class="col-sm-2 col-md-2 col-lg-2"></div>
                      {% endif %}
                  </div>
                  <hr>
                  <p class="def-text" style="white-space: wrap;">{{review.text}}</p>
                  <hr>
                  <div class="row">
                      <div class="col-sm-2 col-md-2 col-lg-2">
                          <p>
                              {% if review.rate >= 0 and review.rate <= 20 %}
                              <span style="background-color: #FF0000; padding-top: 6px; padding-bottom: 6px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"><b>{{review.rate}}</b></span>
                              {% elif review.rate > 20 and review.rate <= 40 %}
                              <span style="background-color: #FF7F00; padding-top: 6px; padding-bottom: 6px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"><b>{{review.rate}}</b></span>
                              {% elif review.rate > 40 and review.rate <= 60 %}
                              <span style="background-color: #FFFF00; padding-top: 6px; padding-bottom: 6px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"><b>{{review.rate}}</b></span>
                              {% elif review.rate > 60 and review.rate <= 80 %}
                              <span style="background-color: #7FFF00; padding-top: 6px; padding-bottom: 6px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"><b>{{review.rate}}</b></span>
                              {% elif review.rate > 80 and review.rate <= 100 %}
                              <span style="background-color: #00FF00; padding-top: 6px; padding-bottom: 6px; padding-left: 10px; padding-right: 10px; border-radius: 10px;"><b>{{review.rate}}</b></span>
                              {% endif %}
                          </p>
                      </div>
                      <div class="col-sm-7 col-md-7 col-lg-7"></div>
                      <div class="col-sm-3 col-md-3 col-lg-3">
                          <p><img src = "{% static 'images/ins/time.png' %}" class="img-btn">  {{review.published_at}}</p>
                      </div>
                  </div>
              </div>
              <br>
            {% endfor %}
        <br>
    </div>
    <div class="col-sm-1 col-md-1 col-lg-1"></div>
</div>
{% endblock %}

templates/ins/ins-list.html
{% extends "base.html" %}

{% block content %}

{% load static %}
{% load custom_tags %}

{% if request.user.admin_or_moder %}
        <br>
        <br>
        <div class="row">
            <div class="col-sm-2 col-md-2 col-lg-2"></div>
            <div class="col-sm-8 col-md-8 col-lg-8">
                <a class="btn btn-create-ins" href="{% url 'ins:add-ins' %}"><i>Додати заклад</i></a>
            </div>
            <div class="col-sm-2 col-md-2 col-lg-2"></div>
        </div>
        <br>
    {% endif %}

<div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
            <br>
            <br>
            <div class="row">
                <div class="col-sm-1 col-md-1 col-lg-1"></div>
                <div class="col-sm-10 col-md-10 col-lg-10">
                    <input type="text" id="search" placeholder="Пошук..." class="form-control">
                    <div id="results" style="display: flex; flex-direction: column;"></div>
                </div>
                <div class="col-sm-1 col-md-1 col-lg-1"></div>
            </div>

            <br>
            <br>
            <div class="container-sm container-md container-lg">
                <div class="ins-container">
                        {% include "ins/list-new.html" %}
                </div>
            </div>
            <br>
            <div class="row">
                    <div class="col-sm-5 col-md-5 col-lg-5"></div>
                    <div class="col-sm-2 col-md-2 col-lg-2">
                        <button id="show-more" class="btn-more" onclick="showMore()">+</button>
                    </div>
                    <div class="col-sm-5 col-md-5 col-lg-5"></div>
                </div>
            <br>
            <nav aria-label="Page navigation example">
                  <ul class="pagination pagination-lg justify-content-center">
                    <li class="page-item">
                        {% if page_obj.has_previous %}
                             <a class="page-link" href="?page={{ page_obj.previous_page_number }}">Попередня</a>
                        {% else %}
                            <a class="page-link disabled">Попередня</a>
                        {% endif %}
                    </li>
                      {% for page_num in page_obj.paginator.page_range %}
                        {% if page_obj.number == page_num %}
                            <li class="page-item active"><a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a></li>
                        {% else %}
                            <li class="page-item"><a href="?page={{ page_num }}" class="page-link">{{ page_num }}</a></li>
                        {% endif %}
                      {% endfor %}
                    <li class="page-item">
                        {% if page_obj.has_next %}
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">Наступна</a>
                        {% else %}
                            <a class="page-link disabled">Наступна</a>
                        {% endif %}
                    </li>
                  </ul>
                </nav>
                <input type="hidden"  id="page-cur" value="{{ page_obj.number }}">
                <input type="hidden"  id="page-num" value="{{ page_obj.paginator.num_pages }}">
            </div>
        <div class="col-sm-1 col-md-1 col-lg-1"></div>
    </div>
    <script>
        const searchInput = document.getElementById('search');
        const resultsDiv = document.getElementById('results');

                // Обробник події 'input' для поля пошуку
        searchInput.addEventListener('input', function() {
            const query = searchInput.value.trim();

                    // Перевірка на порожній запит
            if (query === '') {
                resultsDiv.innerHTML = ''; // Очищуємо результати, якщо запит порожній
                return;
            }

                    // Виконуємо AJAX-запит
            fetch(`/ins/search/results/?query=${encodeURIComponent(query)}`)
                .then(response => response.json())
                .then(data => {
                    resultsDiv.innerHTML = ''; // Очищуємо попередні результати

                        data.results.forEach(item => {
                            const itemElement = document.createElement('a');
                            itemElement.textContent = item.name;
                            itemElement.href = `http://127.0.0.1:8000/ins/ins/${item.id}/`;
                            resultsDiv.appendChild(itemElement)
                        });
                })
                .catch(error => console.error('Помилка при пошуку:', error));
            });
    </script>
    <!--<script>

</script>-->


{% endblock %}

templates/ins/ins_update.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
            <div class="form-create-ins">
            <br>
            <h1 class="def-text" style="text-align: center;">Редагування закладу</h1>
            <br>
            <form method="POST" enctype="multipart/form-data">
              {% csrf_token %}
              {{ form.as_p }}
              <br>
              <button type="submit" class="btn btn-primary">Редагувати</button>
              <a href = "{% url 'ins:ins-detail' ins.pk %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>



{% endblock %}

templates/ins/list-new.html
{% load static %}
{% load custom_tags %}
  {% for ins in institutions %}
    <div class="ins-div">
      {% if ins.media %}
        <div class="row">
          <div class="col-sm-6 col-md-6 col-lg-6">
            <h2 class="def-text" style="text-align: center;"><b>{{ ins.name }}</b></h2>
            <h4>Location<a href="{{ ins.location }}"> <img src="{% static 'images/ins/location-ins.png' %}" style="width: 20px; height:auto"></a></h4>
            <h4>{{ ins.type }}
                {% if ins.type == "Catering" %}
                    <img src="{% static 'images/ins/catering.png' %}" style="width: 55px; height:auto">
                {% elif ins.type == "Sport" %}
                    <img src="{% static 'images/ins/sport.png!sw800' %}" style="width: 50px; height:auto">
                {% elif ins.type == "Entertainment" %}
                    <img src="{% static 'images/ins/entertainment.png' %}" style="width: 35px; height:auto">
                {% elif ins.type == "Education" %}
                    <img src="{% static 'images/ins/education.png' %}" style="width: 40px; height:auto">
                {% elif ins.type == "Trade" %}
                    <img src="{% static 'images/ins/trade.png' %}" style="width: 35px; height:auto">
                {% elif ins.type == "Hotels" %}
                    <img src="{% static 'images/ins/hotels.png' %}" style="width: 30px; height:auto">
                {% elif ins.type == "Beauty and health" %}
                    <img src="{% static 'images/ins/beauty_health.png' %}" style="width: 40px; height:auto">
                {% endif %}
            </h4>
            <h4>Rating
              {% if ins.rating >= 0 and ins.rating <= 20 %}
                <span style="color: #ffd700; font-size: 35px">★</span>
                {% elif ins.rating > 20 and ins.rating <= 40 %}
                   <span style="color: #ffd700; font-size: 35px">★★</span>
                {% elif ins.rating > 40 and ins.rating <= 60 %}
                   <span style="color: #ffd700; font-size: 35px">★★★</span>
                {% elif ins.rating > 60 and ins.rating <= 80 %}
                    <span style="color: #ffd700; font-size: 35px">★★★★</span>
                {% elif ins.rating > 80 and ins.rating <= 100 %}
                   <span style="color: #ffd700; font-size: 35px">★★★★★</span>
                {% endif %}
            </h4>
            <div class="progress" style="margin-top: 80px;">
              <div class="progress-bar" style='width:{{ ins.rating }}%;'>
                {{ ins.rating }}
              </div>
            </div>
              <br>
              <a class="btn btn-info" href="{% url 'ins:ins-detail' ins.pk %}">Детальніше</a>
          </div>
          <div class="col-sm-6 col-md-6 col-lg-6">
                {% if ins.media %}
                        {% if ins.media.url|endswith:".jpg" or ins.media.url|endswith:".png" or ins.media.url|endswith:".jpeg" or ins.media.url|endswith:".webp" %}
                            <img src="{{ ins.media.url }}" alt="Зображення коментаря" class="img-ins">
                        {% elif ins.media.url|endswith:".mp4" %}
                            <video class="img-ins" controls>
                                <source src="{{ ins.media.url }}" type="video/mp4">
                                Your browser does not support the video tag.
                            </video>
                        {% else %}
                            <a href="{{ ins.media.url }}">Завантажити файл</a>
                        {% endif %}
              {% endif %}
          </div>
        </div>
      {% else %}
            <h2 class="def-text" style="text-align: center;"><b>{{ ins.name }}</b></h2>
            <h4>Location<a href="{{ ins.location }}"> <img src="{% static 'images/ins/location-ins.png' %}" style="width: 20px; height:auto"></a></h4>
            <h4>{{ ins.type }}
                {% if ins.type == "Catering" %}
                    <img src="{% static 'images/ins/catering.png' %}" style="width: 55px; height:auto">
                {% elif ins.type == "Sport" %}
                    <img src="{% static 'images/ins/sport.png!sw800' %}" style="width: 50px; height:auto">
                {% elif ins.type == "Entertainment" %}
                    <img src="{% static 'images/ins/entertainment.png' %}" style="width: 35px; height:auto">
                {% elif ins.type == "Education" %}
                    <img src="{% static 'images/ins/education.png' %}" style="width: 40px; height:auto">
                {% elif ins.type == "Trade" %}
                    <img src="{% static 'images/ins/trade.png' %}" style="width: 35px; height:auto">
                {% elif ins.type == "Hotels" %}
                    <img src="{% static 'images/ins/hotels.png' %}" style="width: 30px; height:auto">
                {% elif ins.type == "Beauty and health" %}
                    <img src="{% static 'images/ins/beauty_health.png' %}" style="width: 40px; height:auto">
                {% endif %}
            </h4>
            <h4>Rating
              {% if ins.rating >= 0 and ins.rating <= 20 %}
                <span style="color: #ffd700; font-size: 35px">★</span>
                {% elif ins.rating > 20 and ins.rating <= 40 %}
                   <span style="color: #ffd700; font-size: 35px">★★</span>
                {% elif ins.rating > 40 and ins.rating <= 60 %}
                   <span style="color: #ffd700; font-size: 35px">★★★</span>
                {% elif ins.rating > 60 and ins.rating <= 80 %}
                    <span style="color: #ffd700; font-size: 35px">★★★★</span>
                {% elif ins.rating > 80 and ins.rating <= 100 %}
                   <span style="color: #ffd700; font-size: 35px">★★★★★</span>
                {% endif %}
            </h4>
            <div class="progress">
              <div class="progress-bar" style='width:{{ ins.rating }}%;'    >
                {{ ins.rating }}
              </div>
            </div>
             <br>
              <a class="btn btn-info" href="{% url 'ins:ins-detail' ins.pk %}">Детальніше</a>
      {% endif %}
    </div>
    <br>
    <br>
    {% empty %}
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
            <h1 style="text-align:center;" class="def-text">Немає закладів...</h1>
            <br>
            <br>
            <br>
            <br>
            <br>
            <br>
  {% endfor %}

templates/ins/review_update.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-create-ins">
            <br>
            <h1 class="def-text" style="text-align: center;">Редагування відгуку</h1>
            <br>
            <form method="POST">
              {% csrf_token %}
              {{ form.as_p }}
              <br>
              <button type="submit" class="btn btn-primary">Редагувати</button>
              <a href = "{% url 'ins:ins-detail' review.institution.pk %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}