events/urls.py
from django.urls import path
import events.views as views

urlpatterns = [
    path('calendar/', views.calendar_view, name='calendar'),
    path('calendar/<int:year>/<int:month>/', views.calendar_view, name='calendar_by_date'),
    path('calendar/add-event/<int:year>/<int:month>/<int:day>/', views.EventCreateView.as_view(), name='add_event'),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name = "event-detail"),
    path('event/update/<int:pk>/', views.EventUpdateView.as_view(), name = "event-update"),
    path('event/delete/<int:pk>/', views.EventDeleteView.as_view(), name = "event-delete"),
]

app_name="events"

institutions/urls.py
from django.urls import path
from institutions import views

urlpatterns = [
    path('insts/', views.InstitutionListView.as_view(), name="ins-list"),
    path('ins/<int:pk>/', views.InstitutionDetailView.as_view(), name="ins-detail"),
    path("review-update/<int:pk>/", views.ReviewUpdateView.as_view(), name="review-update"),
    path("review-delete/<int:pk>/", views.ReviewDeleteView.as_view(), name="review-delete"),
    path("add-ins", views.InstitutionCreateView.as_view(), name="add-ins"),
    path("update-ins/<int:pk>/", views.InstitutionUpdateView.as_view(), name="update-ins"),
    path("delete-ins/<int:pk>/", views.InstitutionDeleteView.as_view(), name="delete-ins"),
    path('search/results/', views.SearchView.as_view(), name='search_view'),
    ]

app_name = "ins"

news/urls.py
from django.urls import path
from news import views

urlpatterns = [
    path('new-list/', views.NewListView.as_view(), name='new-list'),
    path('new-create/', views.NewCreateView.as_view(), name="new-create"),
    path('new-update/<int:pk>/', views.NewUpdateView.as_view(), name="new-update"),
    path('new-delete/<int:pk>/', views.NewDeleteView.as_view(), name="new-delete")
]

app_name = "news"

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_page.urls")),
    path('ins/', include('institutions.urls')),
    path("auth/", include("auth_system.urls")),
    path("ad/", include("adverts.urls")),
    path('ev/', include('events.urls')),
    path("walking/", include("walking.urls")),
    path("polls/", include("polls.urls")),
    path("news/", include("news.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

walking/urls.py
from django.urls import path
from walking import views

urlpatterns = [
    path("walks/", views.WalkListView.as_view(), name="walk-list"),
    path("walk/<int:pk>/", views.WalkDetailView.as_view(), name="walk-detail"),
    path("walk-create/", views.WalkCreateView.as_view(), name="walk-create"),
    path("walk-update/<int:pk>/", views.WalkUpdateView.as_view(), name="walk-update"),
    path("walk-delete/<int:pk>/", views.WalkDeleteView.as_view(), name="walk-delete"),
    path("walk-add-ins-ev/<int:pk>/", views.WalkInsEventCreate.as_view(), name="walk-ins-ev")
]

app_name = "walking"

walking/models.py
from django.db import models
from auth_system.models import *
from events.models import Event
from institutions.models import Institution


class Walk(models.Model):
    name = models.CharField(max_length=50, default="Прогулянка")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    goat = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    number_members = models.PositiveIntegerField(default=1)
    type = models.CharField(max_length=50, choices=[
            ('nature', 'Nature'),
            ('city', 'City'),
            ('historic', 'Historic'),
            ('sport', 'Sport'),
        ],
        default='nature')
    status = models.CharField(max_length=20, default="scheduled", choices=[
        ('scheduled', 'Scheduled'),
        ('in_progres', 'In progres'),
        ('completed', 'Completed')
    ])
    institution = models.ManyToManyField("institutions.Institution", null=True, blank=True)
    events = models.ManyToManyField("events.Event",  null=True, blank=True)


    def duration(self):
        return round((self.end_time - self.start_time).total_seconds() / 3600, 1)  # В годинах

    def __str__(self):
        return f"{self.user.username} - {self.created_at}"

    class Meta:
        verbose_name = "Walk"
        verbose_name_plural = "Walk"
        ordering = ["created_at"]

walking/forms.py
from django import forms
from django.core.exceptions import ValidationError
from datetime import datetime, timedelta
from django.utils.timezone import now, make_aware
from .models import Walk

class WalkForm(forms.ModelForm):
    class Meta:
        model = Walk
        fields = ["name", "goat", "start_time", "end_time", "number_members", "type"]

        widgets = {
            'start_time': forms.DateTimeInput(
                attrs={
                    'class': 'form-control',
                    'type': 'datetime-local',
                    'min': now().strftime('%Y-%m-%dT%H:%M'),
                }
            ),
            'end_time': forms.DateTimeInput(
                attrs={
                    'class': 'form-control',
                    'type': 'datetime-local',
                    'min': (now() + timedelta(hours=1)).strftime('%Y-%m-%dT%H:%M'),
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(WalkForm, self).__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Назва..."
        })
        self.fields["name"].label = ''

        self.fields["goat"].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Мета прогулянки, очікування..."
        })
        self.fields["goat"].label = ''

        self.fields["start_time"].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Початковий час..."
        })
        self.fields["start_time"].label = ''

        self.fields["end_time"].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Кінцевий час    ..."
        })
        self.fields["end_time"].label = ''

        self.fields["number_members"].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Кількість учасників..."
        })
        self.fields["number_members"].label = 'Кількість учасників'

        self.fields["type"].widget.attrs.update({
            "class": "form-control",
            "placeholder": "Тип..."
        })
        self.fields["type"].label = 'Тип'

    def clean(self):
        cleaned_data = super().clean()
        start_time = cleaned_data.get("start_time")
        end_time = cleaned_data.get("end_time")

        if start_time and end_time:
            # Приведення до часового поясу
            if start_time.tzinfo is None:
                start_time = make_aware(start_time)
            if end_time.tzinfo is None:
                end_time = make_aware(end_time)

            # Поточний час з урахуванням часового поясу
            current_time = now()

            if start_time < current_time:
                raise ValidationError("Start time cannot be in the past.")
            if end_time <= start_time:
                raise ValidationError("End time must be after start time.")
            if end_time < start_time + timedelta(hours=1):
                raise ValidationError("The difference between start and end time must be at least 1 hour.")
        return cleaned_data


class WalkInsEvForm(forms.ModelForm):
    class Meta:
        model = Walk
        fields = ["institution", "events"]
        widgets = {
            "institution": forms.CheckboxSelectMultiple(),
            "events": forms.CheckboxSelectMultiple(),
        }

    def __init__(self, *args, **kwargs):
        walk = kwargs.pop('walk', None)
        super(WalkInsEvForm, self).__init__(*args, **kwargs)

        # Встановлюємо українські назви для полів
        self.fields["institution"].label = "Заклади: "
        self.fields["events"].label = "Події"

        # Фільтруємо події за датою, якщо передано walk
        if walk and walk.start_time and walk.end_time:
            self.fields["events"].queryset = self.fields["events"].queryset.filter(
                event_date__gte=walk.start_time,
                event_date__lte=walk.end_time,
            )

        # Додаємо клас "form-control" для інших віджетів
        for field_name, field in self.fields.items():
            if not isinstance(field.widget, forms.CheckboxSelectMultiple):
                field.widget.attrs.update({"class": "form-control"})

walking/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView, View
from django.contrib.auth.mixins import LoginRequiredMixin
from walking.models import *
from auth_system.models import *
from walking.mixing import *
from walking.forms import WalkForm, WalkInsEvForm
from datetime import datetime, timedelta
from django.utils import timezone
from django.shortcuts import get_object_or_404
from django.db.models import QuerySet
from django.utils import timezone
from django.db.models import F
from django.utils import timezone

class WalkListView(LoginRequiredMixin, ListView):
    model = Walk
    template_name = "walking/walk-list.html"
    context_object_name = "walks"

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.filter(user=self.request.user)
        now = timezone.now()
        for walk in queryset:
            if walk.start_time < now and walk.status == "scheduled":
                print(walk.status)
                walk.status = "in_progres"
                walk.save()
            if walk.end_time <= now and walk.status == "in_progres":
                walk.status = "completed"
                print("Completed")
                walk.save()
        queryset = queryset.all()
        return queryset


class WalkDetailView(LoginRequiredMixin, UserIsOwnerMixin, DetailView):
    model = Walk
    template_name = "walking/walk-detail.html"
    context_object_name = "walk"

class WalkCreateView(LoginRequiredMixin, CreateView):
    model = Walk
    template_name = "walking/walk-create.html"
    context_object_name = "walk"
    form_class = WalkForm

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy("walking:walk-ins-ev", kwargs={'pk': self.object.pk})
class WalkUpdateView(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Walk
    template_name = "walking/walk-update.html"
    form_class = WalkForm
    context_object_name = "walk"

    def get_success_url(self):
        return reverse_lazy("walking:walk-detail", kwargs={'pk': self.object.pk})

class WalkDeleteView(LoginRequiredMixin, UserIsOwnerMixin, DeleteView):
    model = Walk
    context_object_name = "walk"
    success_url = reverse_lazy("walking:walk-list")

class WalkInsEventCreate(LoginRequiredMixin, UserIsOwnerMixin, UpdateView):
    model = Walk
    template_name = "walking/walk-ins-ev.html"
    form_class = WalkInsEvForm
    context_object_name = "walk"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['walk'] = self.get_object()  # Передаємо об'єкт `walk`
        return kwargs

    def post(self, request, *args, **kwargs):
        walk = self.get_object()
        walk_ins_ev_form = WalkInsEvForm(request.POST, instance=walk)
        if walk_ins_ev_form.is_valid():
            # Нові дані з форми
            new_institutions = walk_ins_ev_form.cleaned_data.get('institution')
            new_events = walk_ins_ev_form.cleaned_data.get('events')

            # Існуючі зв’язки
            current_institutions = set(walk.institution.all())
            current_events = set(walk.events.all())

            # Додати нові зв’язки, яких немає
            institutions_to_add = set(new_institutions) - current_institutions
            events_to_add = set(new_events) - current_events

            walk.institution.add(*institutions_to_add)
            walk.events.add(*events_to_add)

            # Видалити зв’язки, яких більше немає
            institutions_to_remove = current_institutions - set(new_institutions)
            events_to_remove = current_events - set(new_events)

            walk.institution.remove(*institutions_to_remove)
            walk.events.remove(*events_to_remove)

            return redirect('walking:walk-detail', pk=walk.pk)
        else:
            pass

templates/walking/walk-create.html
{% extends "base.html" %}
{% block content %}

{% load static %}

<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-div-walk">
            <br>
            <h1 class="def-text" style="text-align: center;">Створення прогулянки</h1>
            <br>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Створити</button>
                <a href = "{% url 'walking:walk-list' %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/walking/walk-detail.html
{% extends "base.html" %}
{% block content %}

{% load static %}

<br>
<h1 class="def-text" style="text-align:center;">{{ walk.name }}</h1>
<br>
<div class="row">
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="walk-details" style="min-width: max; min-height: 210px;;">
            <h4 class="def-text">{{ walk.goat }}</h4>
        </div>
    </div>
    <div class="col-sm-4 col-md-4 col-lg-4">
        <div class="walk-details">
            <h4 class="def-text" style="padding:5px;">Початок: {{ walk.start_time|date:"F j, Y, H:i" }}</h4>
            <h4 class="def-text" style="padding:5px;">Кінець: {{ walk.end_time|date:"F j, Y, H:i" }}</h4>
            <h4 class="def-text" style="padding: 5px;">Тип: {{ walk.type }}</h4>
            <h4 class="def-text" style="padding:5px;">Тривалість: {{ walk.duration }} год. <img src="{% static './images/walking/duration.png' %}" style="width: 25px; height:auto; margin: 5px;"></h4>
            <div class="row">
                <div class="col-sm-5 col-md-5 col-lg-5">
                    <h5><img src="{% static './images/walking/people.png' %}" style="width: 42px; height:auto; margin: 5px;"> {{ walk.number_members }}</h5>
                </div>
                <div class="col-sm-5 col-md-5 col-lg-5"></div>
                <div class="col-sm-2 col-md-2 col-lg-2">
                    {% if walk.status == 'scheduled' %}
                        <img src="{% static './images/walking/sheduled.png' %}" style="width: 35px; height:auto; margin: 5px;">
                    {% elif walk.status == 'in_progres' %}
                        <img src="{% static './images/walking/in_progress.png' %}" style="width: 35px; height:auto; margin: 5px;">
                    {% elif walk.status == 'completed' %}
                        <img src="{% static './images/walking/completed.png' %}" style="width: 35px; height:auto; margin: 5px;">
                    {% endif %}
                </div>
            </div>
        </div>
        <br>
        <a href="{% url 'walking:walk-ins-ev' walk.pk %}" class="btn btn-info">Додати заклад/подію</a>
        <a href="{% url 'walking:walk-update' walk.pk %}" class="btn btn-warning">Редагувати</a>
        <br>
        <br>
        <form action="{% url 'walking:walk-delete' walk.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="return confirm('Ви справді хочете видалити цю прогулянку?')">Видалити</button>
        </form>

    </div>
</div>
<br>
<h1 class="def-text" style="text-align:center;">Деталі прогулянки</h1>
<br>
<br>
<li class="def-text" style="padding: 10px; font-size: 30px;"><b>Заклади</b></li>
<br>
<br>
<div class="row">
    {% for ins in walk.institution.all %}
    <div class="col-sm-4 col-md-4 col-lg-4">
        <a href="{% url 'ins:ins-detail' ins.pk %}" class="ins-a">
        <div class="div-ins">
            <h4 class="def-text" style="text-align: center;">{{ ins.name }}</h4>
            <br>
            <img src="{{ ins.media.url }}" style="max-width: 100%; height:auto; border-radius: 15px;">
            <br>
            <div class="row">
                <div class="col-sm-3 col-md-3 col-lg-3">
                    <h4 style="margin: 5px;">
                        {% if ins.type == "Catering" %}
                            <img src="{% static 'images/ins/catering.png' %}" style="width: 55px; height:auto">
                        {% elif ins.type == "Sport" %}
                            <img src="{% static 'images/ins/sport.png!sw800' %}" style="width: 50px; height:auto">
                        {% elif ins.type == "Entertainment" %}
                            <img src="{% static 'images/ins/entertainment.png' %}" style="width: 35px; height:auto">
                        {% elif ins.type == "Education" %}
                            <img src="{% static 'images/ins/education.png' %}" style="width: 40px; height:auto">
                        {% elif ins.type == "Trade" %}
                            <img src="{% static 'images/ins/trade.png' %}" style="width: 35px; height:auto">
                        {% elif ins.type == "Hotels" %}
                            <img src="{% static 'images/ins/hotels.png' %}" style="width: 30px; height:auto">
                        {% elif ins.type == "Beauty and health" %}
                            <img src="{% static 'images/ins/beauty_health.png' %}" style="width: 40px; height:auto">
                        {% endif %}
                    </h4>
                </div>
                <div class="col-sm-3 col-md-3 col-lg-3"></div>
                <div class="col-sm-6 col-md-6 col-lg-6">
                    <h4 style="text-align:right;">
                      {% if ins.rating >= 0 and ins.rating <= 20 %}
                        <span style="color: #ffd700; font-size: 35px">★</span>
                        {% elif ins.rating > 20 and ins.rating <= 40 %}
                           <span style="color: #ffd700; font-size: 35px">★★</span>
                        {% elif ins.rating > 40 and ins.rating <= 60 %}
                           <span style="color: #ffd700; font-size: 35px">★★★</span>
                        {% elif ins.rating > 60 and ins.rating <= 80 %}
                            <span style="color: #ffd700; font-size: 35px">★★★★</span>
                        {% elif ins.rating > 80 and ins.rating <= 100 %}
                           <span style="color: #ffd700; font-size: 35px">★★★★★</span>
                        {% endif %}
                    </h4>
                </div>
            </div>
        </div>
        </a>
    </div>
    {% empty %}
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h2 class="def-text" style="text-align:center;"><i>Ще немає закладів...</i></h2>
    </div>
    {% endfor %}
</div>
<br>
<br>
<li class="def-text" style="padding: 10px; font-size: 30px;"><b>Події</b></li>
<br>
<br>
<div class="row">
    {% for event in walk.events.all %}
        <div class="col-sm-12 col-md-12 col-lg-12">
            <a href="{% url 'events:event-detail' event.pk %}" class="ins-a">
            <div class="div-event">
                <h3 class="def-text" style="text-align: center;"><em><b>{{ event.title }}</b></em></h3>
                <br>
                <h5 class="def-text">{{ event.event_date|date:"F j, Y, H:i" }} <img src="{% static './images/walking/event.png' %}" style="width:50px; height: auto;"></h5>
            </div>
            </a>
        </div>
    {% empty %}
    <div class="col-sm-12 col-md-12 col-lg-12">
        <h2 class="def-text" style="text-align: center"><i>Ще немає подій...</i></h2>
    </div>
    {% endfor %}
    </div>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock %}

templates/walking/walk-ins-ev.html
{% extends "base.html" %}
{% block content %}

{% load static %}

<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-div-walk">
            <br>
            <h1 class="def-text" style="text-align: center;">Додавання закладу/події</h1>
            <br>
            <form method="POST">
                {% csrf_token %}
                <br>
                {% if form.institution.field.choices %}
                    <label>{{ form.institution.label }}</label>
                    <br>
                    <br>
                    {{ form.institution }}
                {% else %}
                    <br>
                    <p class="text-danger">Закладів немає.</p>
                    <br>
                {% endif %}
                
                {% if form.events.field.choices %}
                    <br>
                    <label>{{ form.events.label }}</label>
                    <br>
                    {{ form.events }}
                {% else %}
                    <br>
                    <p class="text-danger">Подій немає.</p>
                    <br>
                {% endif %}
                
                <button type="submit" class="btn btn-success">Зберегти</button>
                <a href="{% url 'walking:walk-detail' walk.pk %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}

templates/walking/walk-list.html
{% extends "base.html" %}
{% block content %}

{% load static %}
<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <a class="btn btn-create-walk" href="{% url 'walking:walk-create' %}" ><i>Створити прогулянку</i></a>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
    <div class="row">
        {% for walk in walks %}
        <div class="col-sm-4 col-md-4 col-lg-4">
                <a href="{% url 'walking:walk-detail' walk.pk %}" class="a-walk">
                    <section class="walks">
                        <article class="walk">
                            <h2 class="def-txt" style="text-align:center;">{{ walk.name }}</h2>
                            <br>
                            {% if walk.type == 'nature' %}
                                <img src="{% static './images/walking/nature2.jpg' %}" class="img_type">
                            {% elif walk.type == 'city' %}
                                <img src="{% static './images/walking/city4.png' %}" class="img_type">
                            {% elif walk.type == 'historic' %}
                                <img src="{% static './images/walking/historic.jpg' %}" class="img_type">
                            {% elif walk.type == 'sport' %}
                                <img src="{% static './images/walking/sport.jpg' %}" class="img_type">
                            {% endif %}
                            <br>
                            <div class="row">
                                <div class="col-sm-3 col-md-3 col-lg-3">
                                    <h5><img src="{% static './images/walking/people.png' %}" style="width: 42px; height:auto; margin: 5px;"> {{ walk.number_members }}</h5>
                                </div>
                                <div class="col-sm-7 col-md-7 col-lg-7">

                                </div>
                                <div class="col-sm-2 col-md-2 col-lg-2">
                                    {% if walk.status == 'scheduled' %}
                                        <img src="{% static './images/walking/sheduled.png' %}" style="width: 35px; height:auto; margin: 5px;">
                                    {% elif walk.status == 'in_progres' %}
                                        <img src="{% static './images/walking/in_progress.png' %}" style="width: 35px; height:auto; margin: 5px;">
                                    {% elif walk.status == 'completed' %}
                                        <img src="{% static './images/walking/completed.png' %}" style="width: 35px; height:auto; margin: 5px;">
                                    {% endif %}
                                </div>
                            </div>
                        </article>
                    </section>
                </a>
            <br>
            <br>
            <br>
        </div>
        {% empty %}
            <div class="col-sm-12 col-md-12 col-lg-12">
                <br>
                <br>
                <br>
                <br>
                <br>
                <br>
                <h2 class="def-text" style="text-align:center; "><b>Ще немає прогулянок...</b></h2>
            </div>

        {% endfor %}
    </div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>
    <br>

{% endblock %}

templates/walking/walk-update.html
{% extends "base.html" %}
{% block content %}

{% load static %}
</style>
<br>
<br>
<div class="row">
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
    <div class="col-sm-8 col-md-8 col-lg-8">
        <div class="form-div-walk">
            <br>
            <h1 class="def-text" style="text-align: center;">Оновлення прогулянки</h1>
            <br>
            <form method="POST">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-success">Оновити</button>
                <a href = "{% url 'walking:walk-detail' walk.pk %}" class="btn btn-secondary">Назад</a>
            </form>
            <br>
        </div>
    </div>
    <div class="col-sm-2 col-md-2 col-lg-2"></div>
</div>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

{% endblock %}