adverts/urls.py
from django.urls import path
from adverts import views

urlpatterns = [
    path("advert-list/", views.AdvertListView.as_view(), name="advert-list"),
    path("advert-create/", views.AdvertCreateView.as_view(), name="advert-create"),
    path("advert-update/<int:pk>/", views.AdvertUpdateView.as_view(), name="advert-update"),
    path("advert-delete/<int:pk>/", views.AdvertDeleteView.as_view(), name="advert-delete")
]

app_name = "adverts"

events/urls.py
from django.urls import path
import events.views as views

urlpatterns = [
    path('calendar/', views.calendar_view, name='calendar'),
    path('calendar/<int:year>/<int:month>/', views.calendar_view, name='calendar_by_date'),
    path('calendar/add-event/<int:year>/<int:month>/<int:day>/', views.EventCreateView.as_view(), name='add_event'),
    path('event/<int:pk>/', views.EventDetailView.as_view(), name = "event-detail"),
    path('event/update/<int:pk>/', views.EventUpdateView.as_view(), name = "event-update"),
    path('event/delete/<int:pk>/', views.EventDeleteView.as_view(), name = "event-delete"),
]

app_name="events"

news/urls.py
from django.urls import path
from news import views

urlpatterns = [
    path('new-list/', views.NewListView.as_view(), name='new-list'),
    path('new-create/', views.NewCreateView.as_view(), name="new-create"),
    path('new-update/<int:pk>/', views.NewUpdateView.as_view(), name="new-update"),
    path('new-delete/<int:pk>/', views.NewDeleteView.as_view(), name="new-delete")
]

app_name = "news"

polls/urls.py
from django.urls import path
from polls import views

urlpatterns = [
    path("questions/", views.QuestionListView.as_view(), name="question-list"),
    path("question/<int:pk>/", views.QuestionDetailView.as_view(), name="question-detail"),
    path("question-create/", views.QuestionCreateView.as_view(), name="question-create"),
    path("question-update/<int:pk>/", views.QuestionUpdateView.as_view(), name="question-update"),
    path("question-delete/<int:pk>/", views.QuestionDeleteView.as_view(), name="question-delete"),
    path("choice-update/<int:pk>/", views.ChoiceUpdateView.as_view(), name="choice-update"),
    path("choice-delete/<int:pk>/", views.ChoiceDeleteView.as_view(), name="choice-delete"),
    path("error-answer/<int:question_id>/", views.error_answer_view, name="error-answer")
]

app_name="polls"

system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main_page.urls")),
    path('ins/', include('institutions.urls')),
    path("auth/", include("auth_system.urls")),
    path("ad/", include("adverts.urls")),
    path('ev/', include('events.urls')),
    path("walking/", include("walking.urls")),
    path("polls/", include("polls.urls")),
    path("news/", include("news.urls"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

walking/urls.py
from django.urls import path
from walking import views

urlpatterns = [
    path("walks/", views.WalkListView.as_view(), name="walk-list"),
    path("walk/<int:pk>/", views.WalkDetailView.as_view(), name="walk-detail"),
    path("walk-create/", views.WalkCreateView.as_view(), name="walk-create"),
    path("walk-update/<int:pk>/", views.WalkUpdateView.as_view(), name="walk-update"),
    path("walk-delete/<int:pk>/", views.WalkDeleteView.as_view(), name="walk-delete"),
    path("walk-add-ins-ev/<int:pk>/", views.WalkInsEventCreate.as_view(), name="walk-ins-ev")
]

app_name = "walking"

templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <title>Шептицький</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
    <nav class="sticky-top nav-edit ">
      <div class= "row align-items-center justify-content-center">
          <div class="col-sm-1 col-md-1 col-lg-1"></div>
        <div class = 'col-sm-1 col-md-1 col-lg-1'>
            <a href="{% url 'home:home' %}"><img src="{% static 'images/main/chg-icon.webp' %}" class = "img-icon-nav"></a>
        </div>
          <div class="col-sm-1 col-md-1 col-lg-1"></div>
        <div class = 'col-sm-1 col-md-1 col-lg-1'>
          <a href = "{% url 'adverts:advert-list' %}" class="a-nav">Оголошення</a>
        </div>
        <div class = 'col-sm-1 col-md-1 col-lg-1'>
          <a href = "{% url 'walking:walk-list' %}" class="a-nav">Прогулянки</a>
        </div>
        <div class="col-sm-1 col-md-1 col-lg-1">
            <a href = "{% url 'polls:question-list' %}" class="a-nav">Опитування</a>
        </div>
          <div class="col-sm-1 col-md-1 col-lg-1">
            <a href = "{% url 'ins:ins-list' %}" class="a-nav">Заклади</a>
        </div>
          <div class="col-sm-1 col-md-1 col-lg-1">
            <a href = "{% url 'events:calendar' %}" class="a-nav">Події</a>
        </div>
          <div class="col-sm-1 col-md-1 col-lg-1">
              <a href = "{% url 'news:new-list' %}" class="a-nav">Новини</a>
          </div>
          <div class="col-sm-1 col-md-1 col-lg-1">
                  <a href = "#"><img src="{% static 'images/main/search-icon.png' %}" class = "search-icon-img"></a>
                  {% if request.user.is_authenticated %}
                    <a href = "{% url 'auth:user-profile' request.user.pk %}"><img src="{% static 'images/main/user-icon.png' %}" class = "user-icon-img"></a>
                  {% else %}
                    <a href = "{% url 'auth:login' %}"><img src="{% static 'images/main/user-icon.png' %}" class = "user-icon-img"></a>
                  {% endif %}
          </div>
          <div class="col-sm-1 col-md-1 col-lg-1"></div>
        </div>
    </nav>
    <br>
    {% if request.session.advert %}
        <div class="advert-main" id="advert-main">
            <br>
            <button type="button" class="btn btn-warning" onclick="close_advert()">Закрити</button>
            <h4>{{ request.session.advert }}</h4>
        </div>
    {% endif %}
    <br>
    {% block content %}
    {% endblock %}

    <br>
    <br>
    <footer class="footer">
        <div class="container">
            <div class="footer-section">
                <h4>Адреса:</h4>
                <p>80100, пр.Шевченка,19, м. Шептицький, Шептицький район, Львівська область</p>
                <h4>Телефон:</h4>
                <p>+38(03249) 3-23-46</p>
                <h4>Електронна пошта:</h4>
                <p><a href="mailto:info@sheptytska-rada.gov.ua">info@sheptytska-rada.gov.ua</a></p>
                <h4>Графік праці:</h4>
                <p>Пн-Чт: 08:00-17:15, Пт: 08:00-16:00<br>Обідня перерва: 12:00-13:00</p>
            </div>
            <div class="footer-section">
                <h4>Наші партнери:</h4>
                <ul>
                    <li>Маріямполе, Республіка Литва</li>
                    <li>Пісковіце, Республіка Польща</li>
                    <li>Ксенжполь, Республіка Польща</li>
                    <li>Дрогічин, Республіка Польща</li>
                </ul>
            </div>
            <div class="footer-section">
                <ul class="footer-links">
                    <li><a href="https://sheptytska-rada.gov.ua/Podatkova-sluzhba-informu">Податкова служба інформує</a></li>
                    <li><a href="https://parking.chg.gov.ua/">Штрафи за порушення ПДР</a></li>
                    <li><a href="https://sheptytska-rada.gov.ua/Biuro-tehnichnoi-inventaryzatsii">Бюро технічної інвентаризації</a></li>
                    <li><a href="https://sheptytska-rada.gov.ua/Miskyiy-terytorialnyiy-tsentr-sotsialnogo-obslugovuvannia">Міський територіальний центр соціального обслуговування</a></li>
                    <li><a href="https://sheptytska-rada.gov.ua/Miskyiy-tsentr-sotsialnyh-sluzhb-dlia-simi-diteiy-ta-molodi">Червоноградський міський центр соціальних служб</a></li>
                </ul>
            </div>
            <div class="footer-section footer-social">
                <a href="https://www.facebook.com/Rada.Chervonograda" class="social-link facebook">Вподобай наш Facebook</a>
                <a href="https://www.youtube.com/@%D0%A8%D0%B5%D0%BF%D1%82%D0%B8%D1%86%D1%8C%D0%BA%D0%B0%D0%BC%D1%96%D1%81%D1%8C%D0%BA%D0%B0%D1%80%D0%B0%D0%B4%D0%B0" class="social-link youtube">Підписатись наш Youtube</a>
            </div>
        </div>
        <div class="footer-bottom">
            <p>УВАГА!!! САЙТ СТВОРЕНИЙ ВИКЛЮЧНО В НАВЧАЛЬНИХ ЦІЛЯХ</p>
            <p>Усі дані на сайті неправдиві</p>
        </div>
    </footer>

    <script src="{% static 'js/ins.js' %}"></script>
    <script src="{% static 'js/news.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>